### ISSUE TITLE
Read cell/column value by column name

### ISSUE THREAD

**Issue by grabcityinfo** [mrjono1/FastExcel#15]
How to read column value by column name?

**Comment by Sibz** [comment]
You still have to reference it by its number. A name/letter is essentially an alias for its column number. Index starts at 1 (so Column A = 1).

**Comment by grabcityinfo** [comment]
Suppose I have a ROW and would like to read each cell's value by using COUMN_NAME. How can I do that?
Using INDEX is a good approach for an excel file which does not **change** its columns frequently.

I just want to read values of each COLUMN in a given ROW randomly without using a loop (e.g. for).

**Comment by Sibz** [comment]
Currently there isn't a way to check the column name.

From what I understand is you may have a column named 'MyColumn' but users of the excel file may delete/insert columns to the left therefore changing the index. You need to be able to read the value on a row in 'MyColumn' regardless of where its moved. Does that sound like what you are trying to achieve?

I could expose the ColumnName attribute and you could select it like so:
`Cell myCell = (from c in row where c.ColumnName = "MyColumn" select c);`

Or I could even expose it and provide a that as a function on row (row.GetCellByName(string name) )

**Comment by mrjono1** [comment]
sounds like it could be a good feature addition

**Comment by Sibz** [comment]
@mrjono1 

To provide the ability to use custom cell/column names we would need to load `DefinedNames` from `workbook.xml` and provide a link to `worksheet` from Row/Cell.

To achieve this we could:
1. Add `internal IReadOnlyDictionary DefinedNames<string, string> { get; private set; }` to `SharedStrings` (and load in `SharedStrings` constructor)
2. Pass `worksheet` to constructors of `Row` and `Cell` instead of `SharedStrings`
3. Change references of `SharedStrings` in row/cell classes to `worksheet.FastExcel.SharedStrings`
4. Add `ColumnName`/`CellName` Properties and populate in constructor of `Cell`
`CellName` defaults to `null`, `ColumnName` to the assigned letter.
5. Add function `GetCellByColumnName(string columnName)` to `Row` class

Additionally, as defined names contain which worksheet the cell/column is on, the following functions could be provided in the `FastExcel` class that also trigger loading of worksheet if not already loaded:
- `Cell GetCellByName(string cellName)`
Returns `null` if not found
- `IEnumerable<Cell> GetCellsByColumnName(string columnName, int firstRow = 1, int? count = null)` 
Returns empty collection if not found

**Comment by Sibz** [comment]
^Some slight alterations needed on above suggestions as I just found that:
1. Cells can have multiple names
2. Names can belong to multiple Cells
3. Names can be scoped to a sheet (For cell names only, not column names - thus you can use same name for cell on sheet1/sheet2 but column names are unique across the workbook.

**Comment by grabcityinfo** [comment]
@Sibz

Thanks for your valuable contribution.

That's what we are looking for.
