### ISSUE TITLE
Cells with formulas

### ISSUE THREAD

**Issue by TimSirmovics** [mrjono1/FastExcel#21]
A spreadsheet I am reading contains formulas.
For example cell **H32** contains a formula **=+F32*G32**, which evaluates to **26670**.

Having a look inside the Cell constructor I can see the element for the cell contains both the formula and calculated value:

```
<c r="H32" s="97" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <f>+F32*G32</f>
  <v>26670</v>
</c>
```

However the `Value` property on the cell `XElement` contains the string **"+F32*G3226670"**.

Can we detect when a formula is in use, and read the calculated value as the value of the cell?

**Comment by TimSirmovics** [comment]
Any luck?

**Comment by Sibz** [comment]
Yikes, was a bit jet lagged last week, thanks for the reminder.

**Comment by Sibz** [comment]
Fixed in my branch https://github.com/Sibz/FastExcel/tree/Cells-with-formulas
You can clone that repo and build, or download the compiled DLL here:
[FastExcel-CellFixTest.zip](https://github.com/mrjono1/FastExcel/files/1465555/FastExcel-CellFixTest.zip)

Please let me know how your test goes, and if all is well I will submit pull request.

**Comment by TimSirmovics** [comment]
Hi Sibz,

Thanks for that.

I tried out your change, it didn't work as the v element has a namespace so the `Name == "v"` comparisons fail.

I updated these to `Name.LocalName == "v"` and it works, can you update the branch and i'll test again?

Thanks,

**Comment by Sibz** [comment]
oops, fixed in branch now.

**Comment by TimSirmovics** [comment]
Thanks - looks to be working ok now.
